### ISSUE TITLE
:binary_id compatibility

### ISSUE THREAD

**Issue by lamp-town-guy** [bonfire-networks/needle_ulid#2]
I'm trying to use ULIDs as my primary keys in the DB. But when I try to run my Phoenix app Ecto complains about string format of ULID. It seams it cannot
```
(Ecto.Query.CastError) lib/app/user.ex:55: value `"01F0PBGGWZFR03KSA7H3GKQE6K"` cannot be dumped to type :binary_id in query:

from p0 in Habiter.User.Profile,
  where: p0.user_id == ^"01F0PBGGWZFR03KSA7H3GKQE6K",
  select: p0
```
I'm giving it id I've got from user already in the DB. It should work but it doesn't. There seams to be an easy fix. Problem is then it wouldn't be an ULID format. But as I've seen in https://github.com/erikreedstrom/ulid repo, it is possible to generate UUID format and work with that.

If there's an interest I'm willing to send you a PR with that. Because I don't think it's efficient to use strings as primary keys.

**Comment by jjl** [comment]
We're using `:uuid` everywhere in bonfire. I haven't tried it with binary_id.

**Comment by lamp-town-guy** [comment]
I've found problem to be somewhere else. Because `:uuid` and `:binary_id` are the same thing as far as PostgreSQL is concerned. My solution was to use modified Ecto.UUID which generates ULID. But I hate long URLs. So I investigated it further and swapped my solution for this library. Seems like problem was between chair and a keyboard. It was my suspicion so I closed this issue.
